### PR TITLE
Ruchihegde/workoutview

### PR DESCRIPTION
**Pull request by ruchihegde**
All my workout stuff: WorkoutView, PastWorkout, LiveWorkout, WorkoutSummary, etc.

### CODE REVIEW

**Review by jkruse7 — APPROVED** [review]
I'm in.

**Review by HeyKile — APPROVED** [review]
looks good to me

**Review by HeyKile — CHANGES_REQUESTED** [review]
dude what did you do

**Review by HeyKile — APPROVED** [review]
nvm it's actually so solid so free

**Pull request merged**
